services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transaction-api
    restart: unless-stopped
    environment:
      APP_PORT: ${APP_PORT}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "7000:3000"
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - app	
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false

volumes:
  grafana-data:
