services:
  transaction-api:
    build:
      context: .
      target: production
    container_name: transaction-api
    ports:
      - "7000:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      APP_PORT: ${APP_PORT}
      LOG_INFO: ${LOG_INFO}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped